version: '3'

services:
  app:
    build: .docker
    environment:
      - BINDING=0.0.0.0
    ports:
      - 3001:3000
      - 9000:9000
      - 9999:9999
    volumes:
      - .:/work
    tty: true
    # command:
    #   sh -c "yarn serve"